/*!40030 SET NAMES UTF8 */;
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Maximiliano - Science laboratory 
-- Scientists and laboratory assistants who work with different expreriments and analysis

DROP DATABASE IF EXISTS science_laboratory;
CREATE DATABASE science_laboratory;
USE science_laboratory;


DROP TABLE IF EXISTS Roles;
CREATE TABLE Roles (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS Seniorities;
CREATE TABLE Seniorities (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(15) NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS Workers;
CREATE TABLE Workers (
  id INTEGER NOT NULL AUTO_INCREMENT,
  role_id INTEGER NOT NULL,
  seniority_id INTEGER NOT NULL,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  id_number INTEGER NOT NULL UNIQUE,
  email VARCHAR(40) NOT NULL UNIQUE,
  wage MEDIUMINT NOT NULL,
  phd TINYINT DEFAULT 0,
  PRIMARY KEY (id),
  FOREIGN KEY (role_id) REFERENCES Roles(id) ON UPDATE CASCADE ON DELETE NO ACTION,
  FOREIGN KEY (seniority_id) REFERENCES Seniorities(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

DROP TABLE IF EXISTS Areas;
CREATE TABLE Areas (
  id INTEGER NOT NULL AUTO_INCREMENT,
  wing_id INTEGER NOT NULL,
  name VARCHAR(60) NOT NULL,
  description VARCHAR(50) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (wing_id) REFERENCES LabWings(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

DROP TABLE IF EXISTS WorkersAreas;
CREATE TABLE WorkersAreas (
  id INTEGER NOT NULL AUTO_INCREMENT,
  worker_id INTEGER NOT NULL,
  area_id INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (worker_id) REFERENCES Workers(id) ON UPDATE CASCADE ON DELETE NO ACTION,
  FOREIGN KEY (area_id) REFERENCES Areas(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

DROP TABLE IF EXISTS WorkersExperiments;
CREATE TABLE WorkersExperiments (
  id INTEGER NOT NULL AUTO_INCREMENT,
  worker_id INTEGER NOT NULL,
  experiment_id INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (worker_id) REFERENCES Workers(id) ON UPDATE CASCADE ON DELETE NO ACTION,
  FOREIGN KEY (experiment_id) REFERENCES Experiments(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

DROP TABLE IF EXISTS LabWings;
CREATE TABLE  LabWings  (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(10) NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS Analyses;
CREATE TABLE  Analyses  (
  id INTEGER NOT NULL AUTO_INCREMENT,
  title VARCHAR(60) NOT NULL,
  sample_id INTEGER,
  PRIMARY KEY (id),
  FOREIGN KEY (sample_id) REFERENCES Samples(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

DROP TABLE IF EXISTS Experiments;
CREATE TABLE  Experiments  (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(150) NOT NULL,
  subject_id INTEGER NOT NULL,
  substrate_id INTEGER,
  PRIMARY KEY (id),
  FOREIGN KEY (subject_id) REFERENCES TestSubjects(id) ON UPDATE CASCADE ON DELETE NO ACTION,
  FOREIGN KEY (substrate_id) REFERENCES Substrates(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

DROP TABLE IF EXISTS Substrates;
CREATE TABLE  Substrates  (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(150) NOT NULL,
  health_risk_id INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (health_risk_id) REFERENCES HealthRisks(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

DROP TABLE IF EXISTS Samples;
CREATE TABLE Samples (
	id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(40) NOT NULL,
	tool_id INTEGER NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (tool_id) REFERENCES Tools(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

DROP TABLE IF EXISTS Tools;
CREATE TABLE Tools (
	id INTEGER NOT NULL AUTO_INCREMENT,
	name VARCHAR(40) NOT NULL,
	PRIMARY KEY (id)
);
	
DROP TABLE IF EXISTS ExperimentsAnalyses;
CREATE TABLE  ExperimentsAnalyses  (
  id INTEGER NOT NULL AUTO_INCREMENT,
  experiment_id INTEGER NOT NULL,
  analysis_id INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (experiment_id) REFERENCES Experiments(id) ON UPDATE CASCADE ON DELETE NO ACTION,
  FOREIGN KEY (analysis_id) REFERENCES Analyses(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

DROP TABLE IF EXISTS HealthRisks;
CREATE TABLE  HealthRisks  (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(15) NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS TestSubjects;
CREATE TABLE  TestSubjects  (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  class_id INTEGER NOT NULL,
  health_risk_id INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (class_id) REFERENCES Classes(id) ON UPDATE CASCADE ON DELETE NO ACTION,
  FOREIGN KEY (health_risk_id) REFERENCES HealthRisks(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

DROP TABLE IF EXISTS Classes;
CREATE TABLE  Classes  (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  kingdom_id INTEGER NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (kingdom_id) REFERENCES Kingdoms(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

DROP TABLE IF EXISTS Kingdoms;
CREATE TABLE  Kingdoms  (
  id INTEGER NOT NULL AUTO_INCREMENT,
  name VARCHAR(30) NOT NULL,
  PRIMARY KEY (id)
);
